import type { Metadata } from "next";
import { openSans } from "@/app/ui/fonts";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import "./globals.css";

import CookiesConsent from "./ui/CookieConsent/CookieConsent";

export const metadata: Metadata = {
  title: {
    default: "United4Digital",
    template: "%s - United 4 Digital",
  },
  description: "Generated by create next app",
  twitter: {
    card: "summary_large_image",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="G-FPHQXNL5SQ" />
      <GoogleAnalytics gaId="G-FPHQXNL5SQ" />
      <body
        className={`${openSans.variable} flex flex-col min-h-screen antialiased`}
      >
        <CookiesConsent />
        {children}
      </body>
    </html>
  );
}
